version: '3.6'

services:
  fman-aau:
    container_name: fman-aau-container
    image: cloud.canister.io:5000/muhaftab/fman-backend:latest
    #image: repo.treescale.com/muhaftab/fman-backend:latest
    network_mode: "host"
    environment:
      profile: aau
      port: 8085
    stdin_open: true
    tty: true
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/api/prom/push"
  fman-cyprus:
    container_name: fman-cyprus-container
    image: cloud.canister.io:5000/muhaftab/fman-backend:latest
    #image: repo.treescale.com/muhaftab/fman-backend:latest
    network_mode: "host"
    environment:
      profile: cyprus
      port: 8084
    stdin_open: true
    tty: true
    restart: always
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/api/prom/push"
  fman-swiss:
    container_name: fman-swiss-container
    image: cloud.canister.io:5000/muhaftab/fman-backend:latest
    #image: repo.treescale.com/muhaftab/fman-backend:latest
    network_mode: "host"
    environment:
      profile: swiss
      port: 8086
    stdin_open: true
    tty: true
    restart: always
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/api/prom/push"
  fman-sww:
    container_name: fman-sww-container
    image: cloud.canister.io:5000/muhaftab/fman-backend:latest
    #image: repo.treescale.com/muhaftab/fman-backend:latest
    network_mode: "host"
    environment:
      profile: sww
      port: 8087
    stdin_open: true
    tty: true
    restart: always
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/api/prom/push"
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8097/actuator/health"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
