version: '3.6'

services:
  fman-frontend-aau:
    container_name: fman-frontend-aau-container
    image: cloud.canister.io:5000/XXXXXXXXXXXXXXXX/fman-frontend:latest
    stdin_open: true
    tty: true
    restart: always
    hostname: localhost
    ports:
      ["8092:80"]
    volumes:
      - ./docker_environments/aau:/usr/share/nginx/html/assets/environments
    networks:
      - fman-frontend-net
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/api/prom/push"


networks:
  fman-frontend-net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 10.14.3.1/24

